# Site settings
course_name: Explainability in Machine Learning
course_description: "Algorithmic decision-making is getting more prominent. Machine learning models are regularly helping us with some of the essential aspects of our lives (e.g., healthcare, banking, navigation, etc.). It is of high significance that the end-users correctly understand these models, thereby establishing trust in both the functionality and inference of these models. This new course at IIT Hyderabad introduces the basic notions of explainability and the recent advances in the emerging field of interpretability and explainability in machine learning.."
course_semester: "July-Dec 2024"

baseurl: "/xml" # the subpath of your site, e.g. /blog/
url: "http://krmopuri.github.io/" # the base hostname & protocol for your site

schoolname: "Dept. of AI, IITH"
schoolurl: "https://ai.iith.ac.in/"
#twitter_username: username 

address: |
    Department of Artificial Intelligence
    IIT Hyderabad, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
